CREATE TABLE `CAR_INFORMATION` (
	`CAR_INFORMATION_PK`	VARCHAR(20)	NOT NULL,
	`NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_NAME` (
	`CAR_NAME_PK`	VARCHAR(20)	NOT NULL,
	`NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `YEARS` (
	`YEAR_PK`	VARCHAR(20)	NOT NULL,
	`YEAR`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_INFOR_NAME_YEAR` (
	`CAR_INFOR_NAME_YEAR_PK`	VARCHAR(20)	NOT NULL,
	`CAR_INFORMATION_FK`	VARCHAR(20)	NOT NULL,
	`CAR_NAME_FK`	VARCHAR(20)	NOT NULL,
	`YEAR_FK`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `OPTIONS` (
	`OPTIONS_PK`	VARCHAR(20)	NOT NULL,
	`OPTION`	VARCHAR(300)	NULL
);

CREATE TABLE `YEAR_OPTION` (
	`CAR_INFO_OPTIONS_PK`	VARCHAR(20)	NOT NULL,
	`CAR_INFOR_NAME_YEAR_FK`	VARCHAR(20)	NOT NULL,
	`OPTIONS_FK`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `CAR_INFORMATION` ADD CONSTRAINT `PK_CAR_INFORMATION` PRIMARY KEY (
	`CAR_INFORMATION_PK`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`CAR_NAME_PK`
);

ALTER TABLE `YEARS` ADD CONSTRAINT `PK_YEARS` PRIMARY KEY (
	`YEAR_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `PK_CAR_INFOR_NAME_YEAR` PRIMARY KEY (
	`CAR_INFOR_NAME_YEAR_PK`,
	`CAR_INFORMATION_FK`,
	`CAR_NAME_FK`,
	`YEAR_FK`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`OPTIONS_PK`
);

ALTER TABLE `YEAR_OPTION` ADD CONSTRAINT `PK_YEAR_OPTION` PRIMARY KEY (
	`CAR_INFO_OPTIONS_PK`,
	`CAR_INFOR_NAME_YEAR_FK`,
	`OPTIONS_FK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_CAR_INFORMATION_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`CAR_INFORMATION_FK`
)
REFERENCES `CAR_INFORMATION` (
	`CAR_INFORMATION_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`CAR_NAME_FK`
)
REFERENCES `CAR_NAME` (
	`CAR_NAME_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_YEARS_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`YEAR_FK`
)
REFERENCES `YEARS` (
	`YEAR_PK`
);

ALTER TABLE `YEAR_OPTION` ADD CONSTRAINT `FK_CAR_INFOR_NAME_YEAR_TO_YEAR_OPTION_1` FOREIGN KEY (
	`CAR_INFOR_NAME_YEAR_FK`
)
REFERENCES `CAR_INFOR_NAME_YEAR` (
	`CAR_INFOR_NAME_YEAR_PK`
);

ALTER TABLE `YEAR_OPTION` ADD CONSTRAINT `FK_OPTIONS_TO_YEAR_OPTION_1` FOREIGN KEY (
	`OPTIONS_FK`
)
REFERENCES `OPTIONS` (
	`OPTIONS_PK`
);
