select CAR_INFORMATION.NAME AS "회사이름", CAR_NAME.NAME AS "자동차 이름", YEARS.YEAR AS "연식", COUNT("OPTION") AS "옵션 갯수"
from CAR_INFOR_NAME_YEAR 
INNER JOIN CAR_INFORMATION on CAR_INFOR_NAME_YEAR.CAR_INFORMATION_FK = CAR_INFORMATION.CAR_INFORMATION_PK
INNER JOIN CAR_NAME on CAR_INFOR_NAME_YEAR.CAR_NAME_FK = CAR_NAME.CAR_NAME_PK
INNER JOIN YEARS on CAR_INFOR_NAME_YEAR.YEAR_FK = YEARS.YEAR_PK
INNER JOIN YEAR_OPTION on CAR_INFOR_NAME_YEAR.CAR_INFOR_NAME_YEAR_PK = YEAR_OPTION.CAR_INFOR_NAME_YEAR_FK
INNER JOIN OPTIONS on YEAR_OPTION.OPTIONS_FK = OPTIONS_PK
GROUP BY CAR_INFORMATION.NAME, CAR_NAME.NAME, YEARS.YEAR;
