DELETE FROM Options WHERE FK_CAR = (SELECT PK_CAR FROM Company INNER JOIN Car ON Company.PK_COMPANY = Car.FK_COMPANY WHERE Company.NAME = '벤츠');
DELETE FROM Car WHERE FK_COMPANY IN (SELECT PK_COMPANY FROM Company WHERE NAME = '벤츠');
set sql_safe_updates=0;
DELETE FROM Company WHERE NAME = '벤츠';
