CREATE TABLE `Notice` (
	`NOTICE_PK`	VARCHAR(20)	NOT NULL,
	`WRITER_FK`	VARCHAR(20)	NOT NULL,
	`CONTENT`	VARCHAR(300)	NULL
);

CREATE TABLE `Visitors` (
	`VISITOR_PK`	VARCHAR(20)	NOT NULL,
	`NOTICE_FK`	VARCHAR(20)	NOT NULL,
	`WRITER_FK`	VARCHAR(20)	NOT NULL,
	`VISITOR`	VARCHAR(20)	NULL
);

CREATE TABLE `Writers` (
	`WRITER_PK`	VARCHAR(20)	NOT NULL,
	`WRITER`	VARCHAR(20)	NULL
);

ALTER TABLE `Notice` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`NOTICE_PK`,
	`WRITER_FK`
);

ALTER TABLE `Visitors` ADD CONSTRAINT `PK_VISITORS` PRIMARY KEY (
	`VISITOR_PK`,
	`NOTICE_FK`,
	`WRITER_FK`
);

ALTER TABLE `Writers` ADD CONSTRAINT `PK_WRITERS` PRIMARY KEY (
	`WRITER_PK`
);

ALTER TABLE `Notice` ADD CONSTRAINT `FK_Writers_TO_Notice_1` FOREIGN KEY (
	`WRITER_FK`
)
REFERENCES `Writers` (
	`WRITER_PK`
);

ALTER TABLE `Visitors` ADD CONSTRAINT `FK_Notice_TO_Visitors_1` FOREIGN KEY (
	`NOTICE_FK`
)
REFERENCES `Notice` (
	`NOTICE_PK`
);

ALTER TABLE `Visitors` ADD CONSTRAINT `FK_Notice_TO_Visitors_2` FOREIGN KEY (
	`WRITER_FK`
)
REFERENCES `Notice` (
	`WRITER_FK`
);
