SELECT Notice.CONTENT AS "CONTENT" , Writers.WRITER AS "WRITER", COUNT(Visitors.VISITOR_PK) AS "VISITOR COUNT"
FROM Notice 
INNER JOIN Writers ON Notice.WRITER_FK=Writers.WRITER_PK
INNER JOIN Visitors ON Notice.NOTICE_PK=Visitors.NOTICE_FK
GROUP BY Notice.CONTENT, Writers.WRITER;
